### ISSUE TITLE
Option to specify `JuliaFormatter` option

### ISSUE THREAD

**Issue by saschatimme** [julia-actions/julia-format#8]
I currently don't see a possibility to specify the version of `JuliaFormatter` used. I think it would be very helpful to be able to set this. For example, currently, the latest `JuliaFormatter` version is not used in Atom due to the common `CTSParser` dependency and this leads to different versions used (in the action and locally).
Similarly, a PR can be caught in an update of `JuliaFormatter` and now would need to be rebased (which can be tricky) or to also apply the formatting of the newest version and therefore making the PR much noisier.

**Comment by domluna** [comment]
Good point. I need to transition this to the JS model. You could probably add it as part of a the workflow similarly to how it's done for docs, i.e

```yaml
name: Format

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(name="JuliaFormatter", version="?")'
      - name: Format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using JuliaFormatter; format(".", options...)'
```

Something along these lines should work
